### ISSUE TITLE
pre-v3.3.0 todo

### ISSUE THREAD

**Issue by TysonRayJones** [QuEST-Kit/QuEST#276]
new functions:
- [x] add `calcProbOfOutcomes()` for probability of a multi-qubit sub-state being in a certain outcome
    - [x] code
    - [x] doc
    - [x] unit tests
- [x] add `calcProbOfAllOutcomes()` for probabilities of all outcomes of a multi-qubit sub-state
    - [x] code
    - [x] doc
    - [x] unit tests
- [x] add `multiControlledMultiNot()` for distributed optimised multi-controlled multi-target not 
    - [x] code
    - [x] doc
    - [x] unit tests

refactors:
- [x] phase funcs to specify a new phase for divergence (to avoid exponential number of overrides. Crucial for `SqrtInverseDistance` presently)

unit tests for new functions:
- [x] `applyPhaseFunc()`
- [x] `applyPhaseFuncOverrides()`
- [x] `applyMultiVarPhaseFunc()`
- [x] `applyMultiVarPhaseFuncOverrides()`
- [x] `applyNamedPhaseFunc()`
- [x] `applyNamedPhaseFuncOverrides()`
- [x] `applyParamNamedPhaseFunc()`
- [x] `applyParamNamedPhaseFuncOverrides()`

add additional unit tests (for every func??) on a large state (e.g. 20 qubit), so ensure things like cross-block GPU communication works.
- [ ] calcProbOfAllOutcomes
- [ ] anything else relevant
  
bug fix:
- [x] refactor new QASM utilities (for apply phase functions) to use precision-agnostic printf formatters (remove warnings when compiling `-DPRECISION=1` or `4`)
- [x] refactor testing utilities to report disagreements in precision-agnostic printf
- [ ] fix `-DPRECISION=1` or `4` unit test compiling
- [ ] any CMake build issues reported on github

run ALL tests:
- [ ] multithreaded
    - [ ] single precision
    - [ ] double
    - [ ] quad
- [ ] GPU-accelerated
    - [ ] single
    - [ ] double
- [ ] distributed (2, 4, 8 nodes)
    - [x] single
    - [ ] double
    - [ ] quad

other:
- [ ] update README (clean-up)
- [ ] regenerate doc
